compiler:
  solc:
    remappings:
      - "@ensdomains/ens=ensdomains/ens@0.6.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1-solc-0.7"

dependencies:
  - ensdomains/ens@0.6.0
  - OpenZeppelin/openzeppelin-contracts@3.4.1-solc-0.7
  - skellet0r/resolvers@0.4.1
